<?php
/*
    Speed Language Strings - GuppY PHP Script - version 4.0
    CeCILL Copyright (C) 2004-2006 by Laurent Duveau
    Made by Laurent Duveau, Nicolas Alves, Albert Aymard,
	Jean-Michel Misrachi, Isabelle Marchina and Team
      Web site = http://www.freeguppy.org/
      e-mail   = info@aldweb.com

    Version History :            English language
      v3.0 (25 February 2004)  : initial release by Laurent Duveau
      v4.0 (06 December 2004)  : no change
*/

if (stristr($_SERVER["SCRIPT_NAME"], "en-speed.inc")) {
  header("location:index.php");
  die();
}

$speed1 = "Admin - Connection Speed sample Plugin";
$speed2 = "GuppY comes with a few very simple plugins, as examples (for developers) and as embellishment of your GuppY website (for webmasters).";
$speed3 = "This test calculates the average time needed to download one image from your website to your PC.";
$speed4 = "Accessed by :";
$speed5 = "This plugin registers to the upper modules bar.";
$speed6 = "Try it :";
$speed7 = "Connection Speed";
$speed8 = "Register Connection Speed Plugin in the modules bar : ";
$speed9 = "Estimation being processed...";
$speed10 = "Connection not possible";
$speed11 = "28k Modem Connection";
$speed12 = "56k Modem Connection";
$speed13 = "High Speed Connection";
$speed14 = "Local Connection";
$speed15 = "Kb/sec";
$speed16 = "Estimate the connection speed between your PC and this site";
$speed17 = "Click on the button to get an estimation of the Internet connection speed between your PC and this web site.<br /><br />This test only calculates the average time needed to download one image from this site to your PC.<br /><br />Therefore, the result given is just a download time of one image at a given time. Of course, if you are downloading something else at the same time, the result is underestimated.<br /><br />";
$speed18 = "Launch the evaluation of the connection speed";
$speed19 = "Result :";
?>
