<?php
/*
    Speed Language Strings - GuppY PHP Script - version 4.0
    CeCILL Copyright (C) 2004-2006 by Laurent Duveau
    Made by Laurent Duveau, Nicolas Alves, Albert Aymard,
	Jean-Michel Misrachi, Isabelle Marchina and Team
      Web site = http://www.freeguppy.org/
      e-mail   = info@aldweb.com

    Version History :            French language strings
      v3.0 (25 February 2004)  : initial release by Laurent Duveau
      v4.0 (06 December 2004)  : no change
*/

if (stristr($_SERVER["SCRIPT_NAME"], "fr-speed.inc")) {
  header("location:index.php");
  die();
}

$speed1 = "Admin - Plugin exemple Vitesse de Connexion";
$speed2 = "GuppY est fourni avec quelques plugins très simples, à titre d'exemple (pour les développeurs) et d'embellissement de votre site GuppY (pour les webmasters).";
$speed3 = "Ce test fait une évaluation en calculant le débit moyen pour charger une image depuis votre site web vers votre PC.";
$speed4 = "Accès par :";
$speed5 = "Ce plugin s'inscrit dans la barre de modules haute.";
$speed6 = "Le voir fonctionner :";
$speed7 = "Vitesse de Connexion";
$speed8 = "Inscrire le Plugin Vitesse de Connexion dans la barre de modules : ";
$speed9 = "Evaluation en cours...";
$speed10 = "Connexion impossible";
$speed11 = "Connexion Modem 28k";
$speed12 = "Connexion Modem 56k";
$speed13 = "Connexion Haut débit";
$speed14 = "Connexion locale";
$speed15 = "Ko/sec";
$speed16 = "Evaluation de la vitesse de connexion de votre PC à ce site";
$speed17 = "Cliquez sur le bouton pour évaluer la vitesse de votre connexion entre votre PC et ce site web.<br /><br />Ce test ne fait qu'une évaluation en calculant le débit moyen pour charger une image depuis le site vers votre PC.<br /><br />Le résultat mesure donc la vitesse de chargement d'une image à un moment donnée. Evidemment, si d'autres chargements sont en cours, la mesure est faussée.<br /><br />";
$speed18 = "Lancer l'évaluation de la vitesse de connexion";
$speed19 = "Résultat :";
?>
