<?php
/*
    Clock Language Strings - GuppY PHP Script - version 4.0
    CeCILL Copyright (C) 2004-2006 by Laurent Duveau
    Made by Laurent Duveau, Nicolas Alves, Albert Aymard,
	Jean-Michel Misrachi, Isabelle Marchina and Team
      Web site = http://www.freeguppy.org/
      e-mail   = info@aldweb.com

    Version History :
      v3.0 (25 February 2004)  : initial release
      v4.0 (06 December 2004)  : no change

    ENGLISH language strings
      v3.0 : by Laurent Duveau
*/

if (stristr($_SERVER["SCRIPT_NAME"], "en-clock.inc")) {
  header("location:index.php");
  die();
}

$clock1 = "Admin - Clock sample Plugin";
$clock2 = "GuppY comes with a few very simple plugins, as examples (for developers) and as embellishment of your GuppY website (for webmasters).";
$clock3 = "<b>Clock</b> shows a live digital watch that was made in Javascript.";
$clock4 = "Accessed by : ";
$clock5 = "Basic, by the &lt;A&gt; HTML tag :";
$clock6 = "Try it :";
$clock7 = "Clock";
$clock8 = "Notes :<br />- all that is between [ and ] is facultative<br />- you can also choose the language for display by adding ?lng=xx (where xx=fr or en) at the end of the URL, like this: clock.php?lng=en to run Clock in English.";
?>
