<?php
/*
    Clock Language Strings - GuppY PHP Script - version 4.0
    CeCILL Copyright (C) 2004-2006 by Laurent Duveau
    Made by Laurent Duveau, Nicolas Alves, Albert Aymard,
	Jean-Michel Misrachi, Isabelle Marchina and Team
      Web site = http://www.freeguppy.org/
      e-mail   = info@aldweb.com

    Version History :
      v3.0 (25 February 2004)  : initial release
      v4.0 (06 December 2004)  : no change

    FRENCH language strings
      v3.0 : by Laurent Duveau
*/

if (stristr($_SERVER["SCRIPT_NAME"], "fr-clock.inc")) {
  header("location:index.php");
  die();
}

$clock1 = "Admin - Plugin exemple Horloge";
$clock2 = "GuppY est fourni avec quelques plugins très simples, à titre d'exemple (pour les développeurs) et d'embellissement de votre site GuppY (pour les webmasters).";
$clock3 = "<b>Horloge</b> affiche une montre digitale programmée en Javascript.";
$clock4 = "Accès par :";
$clock5 = "Basique, par la balise HTML &lt;A&gt; :";
$clock6 = "Le voir fonctionner :";
$clock7 = "Horloge";
$clock8 = "Remarques :<br />- ce qui est entre [ et ] est facultatif<br />- vous pouvez aussi indiquer la langue en rajoutant ?lng=xx (où xx=fr ou en) à la fin de l'URL, comme ceci : clock.php?lng=fr pour lancer Horloge en français.";
?>
