<?php
/*
    Clock Sample Plugin Activation - GuppY PHP Script - version 4.0
    CeCILL Copyright (C) 2004-2006 by Laurent Duveau
    Made by Laurent Duveau, Nicolas Alves, Albert Aymard,
	Jean-Michel Misrachi, Isabelle Marchina and Team
      Web site = http://www.freeguppy.org/
      e-mail   = info@aldweb.com

    Version History :
      v3.0 (25 February 2004)  : initial release
      v4.0 (06 December 2004)  : no change
*/

$plugin_bar_name = "";
$plugin_bar_url = "";
$plugin_bar_icon = "";
?>
