  <!-- Palettes de couleurs pour navigateur non compatible  -->
 
<div id=Layer1 style="z-index: 1; left: 650px; visibility: hidden; width: 111px; position: absolute; top: 400px; height: 133px">
<table class="clsCursor" cellspacing="1" cellpadding="1" width="110" bgcolor="#FFFFFF" border="1" summary="">
  <tr>       
  <td height="15" bgColor="#000000" onclick="couleur('#000000')"></td>
  <td bgColor="#444444" onclick="couleur('#444444')"></td>
  <td bgColor="#666666" onclick="couleur('#666666')"></td>
  <td bgColor="#888888" onclick="couleur('#888888')"></td>
  <td bgColor="#aaaaaa" onclick="couleur('#AAAAAA')"></td>
  <td bgColor="#cccccc" onclick="couleur('#CCCCCC')"></td>
  <td bgColor="#ffffff" onclick="couleur('#FFFFFF')"></td>
  </tr><tr>
  <td height="15" bgColor="#ff0000" onclick="couleur('#FF0000')"></td>
  <td bgColor="#400000" onclick="couleur('#400000')"></td>
  <td bgColor="#800000" onclick="couleur('#800000')"></td>
  <td bgColor="#c00000" onclick="couleur('#C00000')"></td>
  <td bgColor="#ff4040" onclick="couleur('#FF4040')"></td>
  <td bgColor="#ff8080" onclick="couleur('#FF8080')"></td>
  <td bgColor="#ffc0c0" onclick="couleur('#FFC0C0')"></td>
  </tr><tr>
  <td height="15" bgColor="#ff7f00" onclick="couleur('#FF7F00')"></td>
  <td bgColor="#462300" onclick="couleur('#462300')"></td>
  <td bgColor="#864200" onclick="couleur('#864200')"></td>
  <td bgColor="#c46100" onclick="couleur('#C46100')"></td>
  <td bgColor="#ffa247" onclick="couleur('#FFA247')"></td>
  <td bgColor="#ffc185" onclick="couleur('#FFC185')"></td>
  <td bgColor="#ffe1c3" onclick="couleur('#FFE1C3')"></td>
  </tr><tr>
  <td height="15" bgColor="#ffff00" onclick="couleur('#FFFF00')"></td>
  <td bgColor="#404000" onclick="couleur('#404000')"></td>
  <td bgColor="#808000" onclick="couleur('#808000')"></td>
  <td bgColor="#c0c000" onclick="couleur('#C0C000')"></td>
  <td bgColor="#ffff40" onclick="couleur('#FFFF40')"></td>
  <td bgColor="#ffff80" onclick="couleur('#FFFF80')"></td>
  <td bgColor="#ffffc0" onclick="couleur('#FFFFC0')"></td>
  </tr><tr>
  <td height="15" bgColor="#00ff00" onclick="couleur('#00FF00')"></td>
  <td bgColor="#004000" onclick="couleur('#004000')"></td>
  <td bgColor="#008000" onclick="couleur('#008000')"></td>
  <td bgColor="#00c000" onclick="couleur('#00C000')"></td>
  <td bgColor="#40ff40" onclick="couleur('#40FF40')"></td>
  <td bgColor="#80ff80" onclick="couleur('#80FF80')"></td>
  <td bgColor="#c0ffc0" onclick="couleur('#C0FFC0')"></td>
  </tr><tr>
  <td height="15" bgColor="#00ffff" onclick="couleur('#00FFFF')"></td>
  <td bgColor="#004040" onclick="couleur('#004040')"></td>
  <td bgColor="#008080" onclick="couleur('#008080')"></td>
  <td bgColor="#00c0c0" onclick="couleur('#00C0C0')"></td>
  <td bgColor="#40ffff" onclick="couleur('#40FFFF')"></td>
  <td bgColor="#80ffff" onclick="couleur('#80FFFF')"></td>
  <td bgColor="#c0ffff" onclick="couleur('#C0FFFF')"></td>
  </tr><tr>
  <td height="15" bgColor="#0000ff" onclick="couleur('#0000FF')"></td>
  <td bgColor="#000040" onclick="couleur('#000040')"></td>
  <td bgColor="#000080" onclick="couleur('#000080')"></td>
  <td bgColor="#0000c0" onclick="couleur('#0000C0')"></td>
  <td bgColor="#4040ff" onclick="couleur('#4040FF')"></td>
  <td bgColor="#8080ff" onclick="couleur('#8080FF')"></td>
  <td bgColor="#c0c0ff" onclick="couleur('#C0C0FF')"></td>
  </tr><tr>
  <td height="15" bgColor="#ff00ff" onclick="couleur('#FF00FF')"></td>
  <td bgColor="#400040" onclick="couleur('#400040')"></td>
  <td bgColor="#800080" onclick="couleur('#800080')"></td>
  <td bgColor="#c000c0" onclick="couleur('#C000C0')"></td>
  <td bgColor="#ff40ff" onclick="couleur('#FF40FF')"></td>
  <td bgColor="#ff80ff" onclick="couleur('#FF80FF')"></td>
  <td bgColor="#ffc0ff" onclick="couleur('#FFC0FF')"></td>
  </tr><tr>
<td colspan="7" class=clsCursor align="center"><font face="verdana" size="2" color="#808080">
<a href="#" onclick="MM_showHideLayers('Layer1','','hide');"><?php echo $web57; ?></a></font></td>
</tr>
</table>
</div>
<div id=Layer2 style="z-index: 2; left: 650px; visibility: hidden; width: 111px; position: absolute; top: 400px; height: 133px">
<table class="clsCursor" cellspacing="1" cellpadding="1" width="110" bgcolor="#FFFFFF" border="1" summary="">
  <tr>
  <td height="15" bgColor="#000000" onclick="surlign('#000000')"></td>
  <td bgColor="#444444" onclick="surlign('#444444')"></td>
  <td bgColor="#666666" onclick="surlign('#666666')"></td>
  <td bgColor="#888888" onclick="surlign('#888888')"></td>
  <td bgColor="#aaaaaa" onclick="surlign('#AAAAAA')"></td>
  <td bgColor="#cccccc" onclick="surlign('#CCCCCC')"></td>
  <td bgColor="#ffffff" onclick="surlign('#FFFFFF')"></td>
  </tr><tr>
  <td height="15" bgColor="#ff0000" onclick="surlign('#FF0000')"></td>
  <td bgColor="#400000" onclick="surlign('#400000')"></td>
  <td bgColor="#800000" onclick="surlign('#800000')"></td>
  <td bgColor="#c00000" onclick="surlign('#C00000')"></td>
  <td bgColor="#ff4040" onclick="surlign('#FF4040')"></td>
  <td bgColor="#ff8080" onclick="surlign('#FF8080')"></td>
  <td bgColor="#ffc0c0" onclick="surlign('#FFC0C0')"></td>
  </tr><tr>
  <td height="15" bgColor="#ff7f00" onclick="surlign('#FF7F00')"></td>
  <td bgColor="#462300" onclick="surlign('#462300')"></td>
  <td bgColor="#864200" onclick="surlign('#864200')"></td>
  <td bgColor="#c46100" onclick="surlign('#C46100')"></td>
  <td bgColor="#ffa247" onclick="surlign('#FFA247')"></td>
  <td bgColor="#ffc185" onclick="surlign('#FFC185')"></td>
  <td bgColor="#ffe1c3" onclick="surlign('#FFE1C3')"></td>
  </tr><tr>
  <td height="15" bgColor="#ffff00" onclick="surlign('#FFFF00')"></td>
  <td bgColor="#404000" onclick="surlign('#404000')"></td>
  <td bgColor="#808000" onclick="surlign('#808000')"></td>
  <td bgColor="#c0c000" onclick="surlign('#C0C000')"></td>
  <td bgColor="#ffff40" onclick="surlign('#FFFF40')"></td>
  <td bgColor="#ffff80" onclick="surlign('#FFFF80')"></td>
  <td bgColor="#ffffc0" onclick="surlign('#FFFFC0')"></td>
  </tr><tr>
  <td height="15" bgColor="#00ff00" onclick="surlign('#00FF00')"></td>
  <td bgColor="#004000" onclick="surlign('#004000')"></td>
  <td bgColor="#008000" onclick="surlign('#008000')"></td>
  <td bgColor="#00c000" onclick="surlign('#00C000')"></td>
  <td bgColor="#40ff40" onclick="surlign('#40FF40')"></td>
  <td bgColor="#80ff80" onclick="surlign('#80FF80')"></td>
  <td bgColor="#c0ffc0" onclick="surlign('#C0FFC0')"></td>
  </tr><tr>
  <td height="15" bgColor="#00ffff" onclick="surlign('#00FFFF')"></td>
  <td bgColor="#004040" onclick="surlign('#004040')"></td>
  <td bgColor="#008080" onclick="surlign('#008080')"></td>
  <td bgColor="#00c0c0" onclick="surlign('#00C0C0')"></td>
  <td bgColor="#40ffff" onclick="surlign('#40FFFF')"></td>
  <td bgColor="#80ffff" onclick="surlign('#80FFFF')"></td>
  <td bgColor="#c0ffff" onclick="surlign('#C0FFFF')"></td>
  </tr><tr>
  <td height="15" bgColor="#0000ff" onclick="surlign('#0000FF')"></td>
  <td bgColor="#000040" onclick="surlign('#000040')"></td>
  <td bgColor="#000080" onclick="surlign('#000080')"></td>
  <td bgColor="#0000c0" onclick="surlign('#0000C0')"></td>
  <td bgColor="#4040ff" onclick="surlign('#4040FF')"></td>
  <td bgColor="#8080ff" onclick="surlign('#8080FF')"></td>
  <td bgColor="#c0c0ff" onclick="surlign('#C0C0FF')"></td>
  </tr><tr>
  <td height="15" bgColor="#ff00ff" onclick="surlign('#FF00FF')"></td>
  <td bgColor="#400040" onclick="surlign('#400040')"></td>
  <td bgColor="#800080" onclick="surlign('#800080')"></td>
  <td bgColor="#c000c0" onclick="surlign('#C000C0')"></td>
  <td bgColor="#ff40ff" onclick="surlign('#FF40FF')"></td>
  <td bgColor="#ff80ff" onclick="surlign('#FF80FF')"></td>
  <td bgColor="#ffc0ff" onclick="surlign('#FFC0FF')"></td>
  </tr><tr>
<td colspan="7" class=clsCursor align="center"><font face="verdana" size="2" color="#808080">
<a href="#" onclick="MM_showHideLayers('Layer2','','hide');"><?php echo $web57; ?></a></font></td>
</tr>
</table>
</div>
