<?php
$type = "ar";
$fileid = "10";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("<!--01-->GuppY");
$fielda2 = stripslashes("<!--01-->GuppY");
$fieldb1 = stripslashes("<!--03-->Configuration");
$fieldb2 = stripslashes("<!--03-->Configuration");
$fieldc1 = stripslashes("<p>
	1. Pour pouvoir configurer votre site, <span style=\"font-weight: bold;\">enregistrez-vous </span>en tant que membre. ( boîte préférences )</p>
<p>
	2. Cliquez sur l\'icône <strong>\"Admin\"</strong> dans la barre du haut.</p>
<p>
	3. Un mot de passe vous est demandé. Saisissez<span style=\"font-weight: bold;\"> \"</span><strong>pass\"</strong> (sans les guillemets) . Mot de passe que vous vous empresserez de changer dans le menu d\'administration !</p>
<p>
	4. Et hop, vous voici sur l\'interface d\'administration.<br />
	<br />
	5. Les deux premiers groupes d\'icônes vous permettent de paramétrer votre site web (langues, apparence, services à activer, etc.), de le maintenir (mais vous n\'en avez pas encore besoin) et de <strong>changer le mot de passe d\'administration</strong> (faites le tout de suite !). Prenez bien le temps de remplir correctement les formulaires qui se trouvent dans les 6 icônes \"Config\".<br />
	Cette étape est <span style=\"text-decoration: underline;\">indispensable</span> .<br />
	<br />
	6. Toutes les autres icônes vous permettent de gérer le contenu de votre site avec une interface intuitive.<br />
	<br />
	<span style=\"background-color: rgb(255, 255, 0);\"><strong>REMARQUES IMPORTANTES</strong></span><br />
	<br />
	- A n\'importe quel moment, vous pouvez remettre le mot de passe à <strong>\"pass\" </strong>juste en rechargeant par FTP le fichier <strong>admin/mdp.</strong></p>
<p>
	- Après transfert FTP de votre site, il est <span style=\"text-decoration: underline;\"><strong>obligatoire </strong>de mettre à jour la configuration générale</span>.</p>
<p>
	-<span style=\"text-decoration: underline;\"> Attention</span>, il vous faudra peut-être modifier les droits des fichiers de configuration de la skin:</p>
<p>
	&nbsp;&nbsp;&nbsp; chmod skin/ma_skin/confskin.inc 666</p>
<p>
	&nbsp;&nbsp;&nbsp; chmod skin/ma_skin/style.css 666</p>
");
$fieldc2 = stripslashes("<p>
	1.To manage the configuration of your site, please <strong>register as member </strong>(<strong>Preferences </strong>box).<br />
	<br />
	2. Click on the <strong>Admin</strong> icon in the top bar.<br />
	<br />
	3. A prompt for a password appears. Key in <strong>\"pass\"</strong> (without the quote marks). You will need to hurry up to change this default password in the administration menu!<br />
	<br />
	4. And there you are in the administration interface.<br />
	<br />
	5. The two first sets of icons are made to set the parameters of your web site (languages, look &amp; feel, services to activate, etc...), to maintain it (but you don\'t need to do it yet) and to <strong>change the administration password</strong> (do it right now !). Take the time to fill in correctly the forms that are called by the 6 \"Config\" icons.<br />
	This step is compulsory.<br />
	<br />
	6. All other icons allow you to manage the content of your web site with a very intuitive interface.<br />
	<br />
	<span style=\"background-color: rgb(255, 255, 0);\"><strong>IMPORTANT NOTICES</strong></span><br />
	<br />
	- At any time, you can reset your password to <strong>\"pass\"</strong> just by uploading back by FTP the&nbsp;&nbsp;&nbsp; <strong>admin/mdp.php</strong> file.</p>
<p>
	<br />
	- After uploading your site by FTP you <span style=\"text-decoration: underline;\"><strong>must </strong>update General management</span>.</p>
<p>
	<br />
	- Perhaps you will need to change accessrights for skin configuration files:</p>
<p>
	<br />
	&nbsp;&nbsp;&nbsp; chmod skin/your_skin/confskin.inc 666</p>
<p>
	<br />
	&nbsp;&nbsp;&nbsp; chmod skin/your_skin/style.css 666</p>
");
$fieldd1 = stripslashes("left");
$fieldd2 = stripslashes("gyslogo.gif");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
