<?php
$type = "ci";
$fileid = "18";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("");
$fielda2 = stripslashes("");
$fieldb1 = stripslashes("");
$fieldb2 = stripslashes("");
$fieldc1 = stripslashes("<p>
	Pourquoi vouloir compliquer ? Essayez <strong>GuppY</strong> simplement ... <img alt=\"smile\" src=\"inc/img/smileys/smile.gif\" /></p>
");
$fieldc2 = stripslashes("<p>
	Why do you want to make things complex? Just try <strong>GuppY</strong>, that\'s all ... <img alt=\"smile\" src=\"inc/img/smileys/smile.gif\" /></p>
");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
