<?php
$type = "ar";
$fileid = "15";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("<!--01-->GuppY");
$fielda2 = stripslashes("<!--01-->GuppY");
$fieldb1 = stripslashes("<!--08-->Don");
$fieldb2 = stripslashes("<!--08-->Donation");
$fieldc1 = stripslashes("<center>
	<h2>
		Nous apprécions votre support</h2>
</center>
<p>
	<br />
	La GuppY Team développe et maintient ce site et ses programmes gratuits sur son temps libre. Cette démarche est complètement gratuite de notre part, sans désir de nous enrichir par ce biais.<br />
	<br />
	Néanmoins, si vous trouvez que <strong>GuppY</strong> vous est utile et si vous souhaitez nous aider à continuer de développer ce site et notre offre de programmes gratuits, vous pouvez toujours nous faire un petit cadeau pour nous encourager.<br />
	<br />
	N\'importe quel montant sera très apprécié, c\'est bien le geste qui compte, selon votre choix en faisant un don ou en adhérant à l\'asso freeGuppY:</p>
<p>
	<img align=\"left\" alt=\"Un cadeau !\" border=\"0\" src=\"img/robot.gif\" /></p>
<h3 style=\"font-weight: bold; font-style: italic; text-align: left;\">
	<span style=\"text-decoration: underline;\">Adhésions : </span></h3>
<ul style=\"margin-left: 120px; text-align: left;\">
	<li>
		<h3 style=\"font-weight: bold; font-style: italic;\">
			15€ pour les particuliers</h3>
	</li>
	<li>
		<h3 style=\"font-weight: bold; font-style: italic;\">
			30€ associations</h3>
	</li>
	<li>
		<h3 style=\"font-weight: bold; font-style: italic;\">
			45€ pour les professionnels.</h3>
	</li>
</ul>
<p>
	Pour nous faire un don ou régler votre adhésion à l\'asso freeGuppY, il vous suffit de saisir le montant souhaité à coté du bouton PayPal de la devise de votre choix, puis de cliquer sur ce bouton PayPal (transaction sécurisée) :</p>
<table align=\"center\" cellspacing=\"10\">
	<tbody>
		<tr>
			<td>
				<form action=\"https://www.paypal.com/cgi-bin/webscr\" method=\"post\">
					<input name=\"cmd\" type=\"hidden\" value=\"_xclick\" /><input name=\"business\" type=\"hidden\" value=\"paypal.asso@freeguppy.org\" /><input name=\"item_name\" type=\"hidden\" value=\"Don de support au projet GuppY\" /><input name=\"page_style\" type=\"hidden\" value=\"PayPal\" /> Montant du don ou de l\'adhésion en USD : <input name=\"amount\" size=\"6\" value=\"22.00\" /><input name=\"currency_code\" type=\"hidden\" value=\"USD\" /><input name=\"no_shipping\" type=\"hidden\" value=\"1\" /><input name=\"no_note\" type=\"hidden\" value=\"1\" /><input name=\"tax\" type=\"hidden\" value=\"0\" /><input name=\"lc\" type=\"hidden\" value=\"FR\" /><input name=\"return\" type=\"hidden\" value=\"\" /><input name=\"cancel_return\" type=\"hidden\" value=\"articles.php?lng=fr&amp;pg=1131\" /> <input align=\"middle\" alt=\"Don en USD\" border=\"0\" name=\"submit\" src=\"img/donate_usd.gif\" type=\"image\" />&nbsp;</form>
			</td>
		</tr>
		<tr>
			<td>
				<form action=\"https://www.paypal.com/cgi-bin/webscr\" method=\"post\">
					<input name=\"cmd\" type=\"hidden\" value=\"_xclick\" /><input name=\"business\" type=\"hidden\" value=\"paypal.asso@freeguppy.org\" /><input name=\"item_name\" type=\"hidden\" value=\"Don de support au projet GuppY\" /><input name=\"page_style\" type=\"hidden\" value=\"PayPal\" /> Montant du don ou de l\'adhésion en EUR : <input name=\"amount\" size=\"6\" value=\"15.00\" /><input name=\"currency_code\" type=\"hidden\" value=\"EUR\" /><input name=\"no_shipping\" type=\"hidden\" value=\"1\" /><input name=\"no_note\" type=\"hidden\" value=\"1\" /><input name=\"tax\" type=\"hidden\" value=\"0\" /><input name=\"lc\" type=\"hidden\" value=\"FR\" /><input name=\"return\" type=\"hidden\" value=\"\" /><input name=\"cancel_return\" type=\"hidden\" value=\"articles.php?lng=fr&amp;pg=1131\" /> <input align=\"middle\" alt=\"Don en EUR\" border=\"0\" name=\"submit\" src=\"img/donate_eur.gif\" type=\"image\" />&nbsp;</form>
				<p>
					&nbsp;</p>
				<p>
					<tt><tt>Pour les adhésions n\'oubliez pas de completer<br />
					le formulaire : </tt></tt><tt><tt><a href=\"http://asso.freeguppy.org/pages/adhesion_net.php?lng=fr\" title=\"adhesion_net.php\"><span style=\"border: 1px dashed rgb(139, 69, 19); padding: 1px 5px; font-weight: bold; color: rgb(255, 0, 0); background-color: rgb(255, 255, 51);\">formulaire </span></a></tt></tt></p>
			</td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>
");
$fieldc2 = stripslashes("<center>
	<h2>
		We appreciate your support</h2>
</center>
<p>
	<br />
	We develop and maintain this web site and its freeware programs during our free time and also when we have a little money left. It is not our philosophy of life to get rich thanks this work.<br />
	<br />
	However, if you like this web site and find <strong>GuppY</strong> useful, please consider making a donation to show your support.<br />
	<br />
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">Any</span> <span class=\"hps\">amount will be</span> <span class=\"hps\">greatly appreciated</span><span>, it\'s</span> <span class=\"hps\">the thought that counts</span><span>,</span> <span class=\"hps\">according to your choice</span> <span class=\"hps\">by making a donation</span> <span class=\"hps\">or joining</span> <span class=\"hps\">the association</span> <span class=\"hps\">freeGuppY</span><span>:</span></span><br />
	<img align=\"left\" alt=\"Un cadeau !\" border=\"0\" src=\"img/robot.gif\" /></p>
<h3 style=\"font-weight: bold; font-style: italic; text-align: left;\">
	<span style=\"text-decoration: underline;\">Subscription : </span></h3>
<ul>
	<li>
		15€ for private</li>
	<li>
		30€ for associations</li>
	<li>
		45€ for professionals</li>
</ul>
<p>
	&nbsp;</p>
<p>
	To donate, you just have to fill in an amount (the one given by default is a suggestion, we had to put one positive number there!) next to the PayPal button of your selected currency), and then click on this button (secured transaction):</p>
<table align=\"center\" cellspacing=\"10\">
	<tbody>
		<tr>
			<td>
				<form action=\"https://www.paypal.com/cgi-bin/webscr\" method=\"post\">
					<input name=\"cmd\" type=\"hidden\" value=\"_xclick\" /><input name=\"business\" type=\"hidden\" value=\"paypal.asso@freeguppy.org\" /><input name=\"item_name\" type=\"hidden\" value=\"Don de support au projet GuppY\" /><input name=\"page_style\" type=\"hidden\" value=\"PayPal\" /> Donation amount USD : <input name=\"amount\" size=\"6\" value=\"22.00\" /><input name=\"currency_code\" type=\"hidden\" value=\"USD\" /><input name=\"no_shipping\" type=\"hidden\" value=\"1\" /><input name=\"no_note\" type=\"hidden\" value=\"1\" /><input name=\"tax\" type=\"hidden\" value=\"0\" /><input name=\"lc\" type=\"hidden\" value=\"FR\" /><input name=\"return\" type=\"hidden\" value=\"\" /><input name=\"cancel_return\" type=\"hidden\" value=\"articles.php?lng=fr&amp;pg=1131\" /> <input align=\"middle\" alt=\"Don en USD\" border=\"0\" name=\"submit\" src=\"img/donate_usd.gif\" type=\"image\" />&nbsp;</form>
			</td>
		</tr>
		<tr>
			<td>
				<form action=\"https://www.paypal.com/cgi-bin/webscr\" method=\"post\">
					<input name=\"cmd\" type=\"hidden\" value=\"_xclick\" /><input name=\"business\" type=\"hidden\" value=\"paypal.asso@freeguppy.org\" /><input name=\"item_name\" type=\"hidden\" value=\"Don de support au projet GuppY\" /><input name=\"page_style\" type=\"hidden\" value=\"PayPal\" /> Donation amount EUR : <input name=\"amount\" size=\"6\" value=\"15.00\" /><input name=\"currency_code\" type=\"hidden\" value=\"EUR\" /><input name=\"no_shipping\" type=\"hidden\" value=\"1\" /><input name=\"no_note\" type=\"hidden\" value=\"1\" /><input name=\"tax\" type=\"hidden\" value=\"0\" /><input name=\"lc\" type=\"hidden\" value=\"FR\" /><input name=\"return\" type=\"hidden\" value=\"\" /><input name=\"cancel_return\" type=\"hidden\" value=\"articles.php?lng=fr&amp;pg=1131\" /> <input align=\"middle\" alt=\"Don en EUR\" border=\"0\" name=\"submit\" src=\"img/donate_eur.gif\" type=\"image\" />&nbsp;</form>
				<h3>
					<tt>please fill in the form below<span style=\"text-align: right;\"> :</span></tt><tt><a href=\"http://asso.freeguppy.org/pages/adhesion_net.php?lng=en\" title=\"adhesion_net.php\"><span style=\"border: 1px dashed rgb(139, 69, 19); padding: 1px 5px; font-weight: bold; color: rgb(255, 0, 0); background-color: rgb(255, 255, 51);\">Subscription form</span></a></tt></h3>
			</td>
		</tr>
	</tbody>
</table>
<p>
	&nbsp;</p>
");
$fieldd1 = stripslashes("left");
$fieldd2 = stripslashes("aldsmall.gif");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
?>