<?php
$type = "ar";
$fileid = "14";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("<!--01-->GuppY");
$fielda2 = stripslashes("<!--01-->GuppY");
$fieldb1 = stripslashes("<!--07-->Licence");
$fieldb2 = stripslashes("<!--07-->License");
$fieldc1 = stripslashes("<p>
	GuppY est distribué gratuitement sous licence libre <strong>CeCILL</strong> (voir ci-dessous) <img alt=\"\" border=\"0\" src=\"inc/img/smileys/smile.gif\" /><br />
	<br />
	Ceci signifie que vous pouvez utiliser gratuitement ce script, le modifier pour votre usage propre.</p>
<p>
	Conformément à l\'article 6 du CONTRAT DE LICENCE DE LOGICIEL LIBRE CeCILL <span style=\"text-decoration: underline;\">il est interdit de retirer le copyright dans le pied de page</span>.</p>
<p>
	Si vous en distribuez une version modifiée, elle doit elle-même suivre les termes de la licence libre CeCILL.</p>
<p>
	&nbsp;</p>
<p>
	<strong>NOUS NE POURRONS EN AUCUN CAS ETRE TENUS POUR RESPONSABLES DES PROBLEMES QUI POURRAIENT RESULTER DE L\'UTILISATION DE CE SCRIPT.</strong></p>
<p>
	&nbsp;</p>
<hr />
<p>
	<iframe frameborder=\"0\" height=\"480\" scrolling=\"yes\" src=\"copyright-fr.htm\" width=\"100%\"></iframe></p>
");
$fieldc2 = stripslashes("<p>
	GuppY is distributed freely under the terms of the <strong>CeCILL</strong> license (see here under) <img alt=\"\" border=\"0\" src=\"inc/img/smileys/smile.gif\" /><br />
	<br />
	It means that you can use this script for free, modify it for your own use.</p>
<p>
	If you distribute a modified version of it, this modified version has to comply to the CeCILL free Licence as well.</p>
<p>
	Acording to article number 6 of the CeCILL FREE LICENCING AGREEMENT, <span style=\"text-decoration: underline;\">discarding copyright at end of page is strictly forbidden</span>.</p>
<p>
	<br />
	<strong>WE CAN IN NO WAY BE LIABLE FOR POSSIBLE DAMAGES THAT COULD OCCUR DUE TO THE USE OF THIS SCRIPT.</strong></p>
<p>
	&nbsp;</p>
<hr />
<p>
	<iframe frameborder=\"0\" height=\"480\" scrolling=\"yes\" src=\"copyright-en.htm\" width=\"100%\"></iframe></p>
");
$fieldd1 = stripslashes("left");
$fieldd2 = stripslashes("gyslogo.gif");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
