<?php
$type = "ar";
$fileid = "12";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("<!--01-->GuppY");
$fielda2 = stripslashes("<!--01-->GuppY");
$fieldb1 = stripslashes("<!--05-->Fonctionnement interne");
$fieldb2 = stripslashes("<!--05-->Internal running");
$fieldc1 = stripslashes("<p>
	Répétons le encore une fois, <strong>GuppY</strong> n\'utilise <span style=\"text-decoration:underline;\">pas</span> de base de données externe de type MySQL.</p>
<p>
	Ceci permet une grande souplesse et de multiples avantages :</p>
<ul>
	<li style=\"margin-left: 10px;\">
		quasiment tous les hébergeurs Internet sont possibles (ils doivent juste offrir le service du langage de script PHP dans lequel est écrit GuppY).</li>
</ul>
<ul>
	<li style=\"margin-left: 10px;\">
		il n\'y a pas de compétence technique en installation de base de données à posséder (cf la procédure ultra simple d\'installation de GuppY).</li>
</ul>
<ul>
	<li style=\"margin-left: 10px;\">
		l\'affichage des pages est grandement accéléré, la gestion de la base de données étant généralement le maillon faible des hébergeurs.</li>
</ul>
<ul>
	<li style=\"margin-left: 10px;\">
		Les informations gérées par GuppY sont enregistrées dans des fichiers texte (au format <strong>.dtb</strong>) ou PHP (au format <strong>.inc</strong>) dans le dossier <strong>data/</strong>.</li>
</ul>
<p>
	&nbsp;</p>
");
$fieldc2 = stripslashes("<p>
	Let\'s say it one more time, GuppY does <span style=\"text-decoration:underline;\">not</span> require the use of an database like MySQL.</p>
<p>
	This provides a great flexibility and many advantages :</p>
<ul>
	<li>
		almost all Internet hosts can be chosen (they just need to offer the PHP scripting language in which GuppY is written).</li>
</ul>
<ul>
	<li>
		there is no need for a very sophisticated knowledge in installing a database (please refer to the very simple installation procedure of GuppY).</li>
</ul>
<ul>
	<li>
		the display of pages is highly accelerated as the database management is usually the bottle neck of the Internet hosts.</li>
</ul>
<ul>
	<li>
		bug correction in tracking hits.</li>
</ul>
<ul>
	<li>
		The information managed by GuppY is stored in text files (with a <strong>.dtb</strong> format) or PHP files (with a <strong>.inc</strong> format) in the <strong>data/</strong> directory.</li>
</ul>
");
$fieldd1 = stripslashes("left");
$fieldd2 = stripslashes("gyslogo.gif");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
