<?php
$type = "ar";
$fileid = "16";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("<!--02-->Communauté GuppY");
$fielda2 = stripslashes("<!--02-->GuppY community");
$fieldb1 = stripslashes("<!--01-->Nous rejoindrez-vous ?");
$fieldb2 = stripslashes("<!--01-->Will you join us?");
$fieldc1 = stripslashes("<p>
	Si vous appréciez <strong>GuppY</strong> et que vous souhaitez nous aider à le promouvoir et le développer, soyez le bienvenu.<br />
	<br />
	Voici quelques points d\'améliorations possibles et sur lesquels votre aide sera précieuse (il y en a pour tous les goûts) :</p>
<p>
	<br />
	- Des traducteurs natifs dans toutes les langues pour nous aider à faire vivre le contenu bilingue du site officiel de GuppY.</p>
<p>
	<br />
	- Débogage, amélioration du code source.</p>
<p>
	<br />
	- Nouvelles fonctionnalités.</p>
<p>
	<br />
	- Toute idée que vous aurez.</p>
");
$fieldc2 = stripslashes("<p>
	If you like <strong>GuppY</strong> and you wish to help us promote and develop it, you are very welcome.<br />
	<br />
	Here are a few ideas to improve it and for which your help will be more than welcome (there are improvements for all kinds of good willing people):</p>
<p>
	<br />
	- Native translators into all languages for helping us to have the bilingual content of the GuppY official website live.</p>
<p>
	<br />
	- Debugging, source code improvement.</p>
<p>
	<br />
	- New functionalities.</p>
<p>
	<br />
	- Any idea that you will have.</p>
");
$fieldd1 = stripslashes("left");
$fieldd2 = stripslashes("gyteam.gif");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
