<?php
$type = "ar";
$fileid = "29";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("<!--02-->Communauté GuppY");
$fielda2 = stripslashes("<!--02-->GuppY community");
$fieldb1 = stripslashes("<!--02-->Remerciements");
$fieldb2 = stripslashes("<!--02-->Thanks");
$fieldc1 = stripslashes("<p>
	J\'ai commencé ce projet seul et j\'ai travaillé pendant 3 mois dessus avant de poster en ligne la version 1.0 de miniPortail. Certaines personnes se montrèrent très vite enthousiastes au sujet de miniPortail si bien qu\'elles me rejoignirent bien vite dans l\'aventure.</p>
<p>
	<strong>MERCI A VOUS TOUTES ET TOUS</strong> pour votre fidélité et votre confiance dans ce projet.<br />
	<br />
	Je devrais écrire ici un petit mot pour chacun et chacune, ceux qui ont fait cet énorme travail de traduire miniPortail / GuppY dans d\'autres langues (Damski fut le premier à porter miniPortail dans une autre langue, en l\'occurrence l\'Espagnol), ceux qui m\'alimentèrent de bonnes idées et de suggestions (je pense tout spécialement à Don, Cees, et tant d\'autres), ceux qui me reportèrent des bugs (et qui ne se sont jamais plaints de ces bugs), et même ceux qui m\'envoyèrent des injures !<br />
	<br />
	Mais, j\'oublierais l\'un ou l\'autre d\'entre vous et je m\'en sentirais tellement confus et désespéré que je vais me contenter ici de donner un <strong>MERCI TOUT SPECIAL</strong> à ceux qui, tous les jours, travaillent dur sur le projet GuppY.</p>
<p>
	Je garde une pensée particulière pour <span style=\"font-weight: bold;\">Alex</span>, le premier à m\'avoir rejoint, pour <span style=\"font-weight: bold;\">Nicolas</span>, bouillonnant d\'idées et auteur de nombreux scripts pour GuppY, pour<strong> Icare</strong> à l\'origine du nouveau look de GuppY et <strong>Jean-Mi</strong> est un expert es plug-ins, un vrai pro du PHP.<br />
	<br />
	Oui, <strong>UN GRAND MERCI</strong> à vous tous, membres de la dite \"<strong>GuppY Team</strong>\".</p>
<p>
	Retrouvrez les tous les jours sur le site officiel de GuppY: <a href=\"http://www.freeguppy.org/\" target=\"_blank\">http://www.freeguppy.org</a>.</p>
<p>
	N\'oubliez jamais qu\'ils sont bénévoles et vous aident sur leur temps libre, que courtoisie et gentillesse sont donc de mise avec la \"<strong>GuppY Team</strong>\".<br />
	&nbsp;</p>
<p>
	&nbsp;</p>
<p>
	<br />
	&nbsp;</p>
");
$fieldc2 = stripslashes("<p>
	I started alone this project and worked on it for 3 months before posting online the version 1.0 of miniPortail. Some people got enthousiastic about miniPortail and they pretty soon joined me. <strong>THANK YOU GIRLS AND GUYS</strong> for your fidelity and confidence in this project.<br />
	<br />
	I should write here about all people, those that did this great work of translating miniPortail / GuppY to other languages (Damski was the first one to translate miniPortail to another language, being Spanish), those that provided me with good ideas and suggestions (I especially think about Don, Cees, and many others), those that kindly reported bugs (and that never complained about them), and even those that insulted me because of this portal !<br />
	<br />
	But, I would forget one or two of you and feel so sorry about it that I will then just give a <strong>VERY SPECIAL THANK YOU</strong> to those that work hard on the GuppY project on a daily basis.</p>
<p>
	And I don\'to forget <span style=\"font-weight: bold;\">Alex</span>, historically the first to join me and <span style=\"font-weight: bold;\">Nicolas</span> who made a lot of scripts for GuppY, <span id=\"result_box\" lang=\"en\"><strong><span class=\"hps alt-edited\">Icare</span></strong> <span class=\"hps\">to</span> <span class=\"hps\">the origin of the</span> <span class=\"hps\">new look</span> <span class=\"hps\">GuppY</span> <span class=\"hps\">and</span> <strong><span class=\"hps\">Jean</span><span>-Mi</span></strong> <span class=\"hps\">is an</span> <span class=\"hps\">expert in plug</span><span>-ins</span><span>, a</span> <span class=\"hps\">great PHP</span><span> developper.</span></span><br />
	<br />
	Yes, a <strong>HUGE THANK YOU</strong> to all of you, members of the so called \"<strong>GuppY Team</strong>\".</p>
<p>
	Find them every day on the official GuppY website : <a href=\"http://www.freeguppy.org/\" target=\"_blank\">http://www.freeguppy.org</a>.</p>
<p>
	Please never forget that they are unpaid and help you on their free time, that you should always be courteous and kind with the \"<strong>GuppY Team</strong>\".</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
");
$fieldd1 = stripslashes("left");
$fieldd2 = stripslashes("gyteam.gif");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
?>