<?php
$type = "gb";
$fileid = "26";
$status = "a";
$creadate = "200412060400";
$moddate = "200412060400";
$author = stripslashes("aldweb");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("1");
$fielda2 = stripslashes("");
$fieldb1 = stripslashes("http://www.aldweb.com/");
$fieldb2 = stripslashes("");
$fieldc1 = stripslashes("Initiateur de <strong>GuppY</strong>, je suis très heureux d\'être le premier à signer le livre d\'or de votre site réalisé avec <strong>GuppY</strong> <img src=\"inc/img/smileys/smile.gif\" alt=\"smile\" /><br /><br />Initiator of <strong>GuppY</strong>, I am very happy to be the first person to sign in the guestbook of your web site made with <strong>GuppY</strong> <img src=\"inc/img/smileys/smile.gif\" alt=\"smile\" />");
$fieldc2 = stripslashes("");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
?>