<?php
$type = "rs";
$fileid = "27";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("aldweb Site");
$fielda2 = stripslashes("aldweb Site");
$fieldb1 = stripslashes("http://www.aldweb.com/data/newsfr.xml");
$fieldb2 = stripslashes("http://www.aldweb.com/data/newsen.xml");
$fieldc1 = stripslashes("");
$fieldc2 = stripslashes("");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
?>
