<?php
$type = "ci";
$fileid = "21";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("");
$fielda2 = stripslashes("");
$fieldb1 = stripslashes("");
$fieldb2 = stripslashes("");
$fieldc1 = stripslashes("<p>
	Votre premier réflexe après le téléchargement de GuppY ? Lire le <a href=\"articles.php?lng=fr&amp;pg=43\"><strong>lisezmoi.txt</strong> !!!</a></p>
");
$fieldc2 = stripslashes("<p>
	Your first reflex after you have downloaded GuppY ? Read the <a href=\"articles.php?lng=en&amp;pg=43\"><strong>readme.txt</strong> !!!</a></p>
");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
