<?php
$type = "fa";
$fileid = "24";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("");
$fielda2 = stripslashes("");
$fieldb1 = stripslashes("Quel est le lien entre <b>GuppY</b>, Phortail, Portix et Minicontent ?");
$fieldb2 = stripslashes("");
$fieldc1 = stripslashes("<p>
	De tous les petits portails web que j\'ai pu trouver dans ma recherche du portail idéal, c\'est de loin Phortail qui avait l\'interface utilisateur que j\'ai trouvée la plus sympathique. De plus le concept et l\'architecture de Phortail étaient bons. Mais le script PHP de Phortail nécessitait une sérieuse remise en cause. C\'était en 2003<br />
	<br />
	Aussi, <b>GuppY</b> trouve une certaine source d\'inspiration dans Phortail, mais il faut savoir que le code PHP de <b>GuppY</b> a été écrit à 100% \"from scratch\" pour être plus efficace, plus extensible et plus sûr.<br />
	<br />
	En final, voici résumées les sources d\'inspiration des 3 outils Phortail, Portix et Minicontent sur <b>GuppY</b> :<br />
	- Phortail : le concept général (dont la non utilisation de base de données externe) et l\'apparence générale<br />
	- Portix : le concept sans base de données externe, les citations... et la volonté de faire plus simple...<br />
	- Minicontent : le bilinguisme et le menu articles avec rubriques</p>
");
$fieldc2 = stripslashes("<p>
	Starting point was Phortail, Portix ans Mini ; keeping the basic features, no external database, built-in bilingualism, Aldweb wrote the script from scratch in 2003 to become faster and safer.</p>
");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
