<?php
$type = "rs";
$fileid = "28";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("freeGuppY");
$fielda2 = stripslashes("freeGuppY");
$fieldb1 = stripslashes("http://www.freeguppy.org/data/newsfr.xml");
$fieldb2 = stripslashes("http://www.freeguppy.org/data/newsen.xml");
$fieldc1 = stripslashes("");
$fieldc2 = stripslashes("");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
?>
