<?php
$type = "ne";
$fileid = "25";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("");
$fielda2 = stripslashes("");
$fieldb1 = stripslashes("Première nouvelle");
$fieldb2 = stripslashes("First news");
$fieldc1 = stripslashes("<p>Ce nouveau site a été créé avec le CMS <a href=\"http://www.freeguppy.org/\">GuppY</a> en version 4.6.21&nbsp; <img alt=\"\" border=\"0\" src=\"inc/img/smileys/smile.gif\" /></p>

<p>Déjà doté de multiples fonctionnalités, la GuppY Team lui a adjoint un espace de téléchargement afin de personnaliser votre site: <a href=\"http://guppyland.freeguppy.org/index.php\" target=\"_blank\"><strong>GuppYLand</strong></a>.</p>

<p>Sur <span style=\"font-weight: bold;\">GuppYLand</span> nous présentons des plugins, skins, add-ons issus de la communauté GuppY ainsi que des éléments graphiques susceptibles d\'équiper votre GuppY et de vous aider à le customiser.</p>
");
$fieldc2 = stripslashes("<p>This new web site has been made with <a href=\"http://www.freeguppy.org/\">GuppY</a>release 4.6.21 <img alt=\"\" border=\"0\" src=\"inc/img/smileys/smile.gif\" /></p>

<p><a href=\"http://guppyland.freeguppy.org/\" title=\"GuppYLand\"><strong>GuppYLand</strong></a> is aimed at being an extension of freeGuppY, where plugins will be stored and exposed, plus skins, add-ons and all graphical elements that could make your GuppY more attractive and help you to have it look the way you want to.</p>
");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
