<?php
$type = "ci";
$fileid = "20";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("");
$fielda2 = stripslashes("");
$fieldb1 = stripslashes("");
$fieldb2 = stripslashes("");
$fieldc1 = stripslashes("Prenez un bon contenu, une pincée de pixels, laissez reposer, vous obtenez un <strong>GuppY</strong> des plus harmonieux.");
$fieldc2 = stripslashes("Take good contents, a pinch of pixels, let rest and you obtain an harmonious <strong>GuppY</strong>.");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
?>