<?php
$type = "ci";
$fileid = "22";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("");
$fielda2 = stripslashes("");
$fieldb1 = stripslashes("");
$fieldb2 = stripslashes("");
$fieldc1 = stripslashes("N\'oubliez pas d\'installer un <strong>htaccess</strong> pour protéger l\'accès à la zone d\'administration de <strong>GuppY</strong>.");
$fieldc2 = stripslashes("Don\'t forget to install an <strong>htaccess</strong> to protect the access to the admin zone of <strong>GuppY</strong>.");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
?>