<?php
$type = "fa";
$fileid = "23";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("");
$fielda2 = stripslashes("");
$fieldb1 = stripslashes("Pourquoi avez-vous développé <b>GuppY</b> ?");
$fieldb2 = stripslashes("Why did you develop <b>GuppY</b>?");
$fieldc1 = stripslashes("<p>
	Deux raisons principales m\'ont poussé à développer <strong>GuppY</strong>, car je voulais un petit portail pour mon site web perso (<a href=\"http://www.aldweb.com/\" target=\"_blank\">aldweb Site</a>) qui permette :<br />
	<br />
	- une gestion bilingue du contenu, l\'utilisateur choisissant sa langue à l\'entrée sur le site. Seul Minicontent répondait à cette contrainte... mais avec une base de données MySQL à installer et peu de fonctionnalités hors le CMS (Contact Management System).<br />
	<br />
	- un script simple ne s\'appuyant pas sur une base de données. Mon regard s\'est alors porté sur Portix et Phortail. Le premier, Portix, est en plein développement mais il commence à devenir complexe et, dernière nouveauté, il apporte une gestion des utilisateurs dont je ne voulais pas. Le second, Phortail, était beaucoup plus basique, simpliste même, mais il était sain. Ce fut donc une source d\'inspiration pour mon développement de <strong>GuppY</strong>.<br />
	<br />
	Finalement, je me suis décidé à me lancer dans l\'écriture de mon propre script, avec l\'idée de le partager, et donc de le rendre aussi \"convivial\" que possible. Et voilà comment <strong>GuppY</strong> est né <img alt=\"eek\" src=\"inc/img/smileys/eek.gif\" /></p>
");
$fieldc2 = stripslashes("<p>
	Two main reasons lead me to develop <strong>GuppY</strong>. I wanted a small portal for my own personal web site (<a href=\"http://www.aldweb.com/\" target=\"_blank\">aldweb Site</a>) that would allow:<br />
	<br />
	- a native bilingual management of the content, the user only having to choose his language when getting on the site. Only Minicontent answered to this constraint... but it required to install a MySQL database and few functionalities were available apart from the standard CMS (Contact Management System).<br />
	<br />
	- a simple script that would not require a database. I then looked at Portix and Phortail. The first one, Portix, is in great development but it is starting to become quite complex and, last news, it now comes with a user management which I did not want of. The second one, Phortail, was much more simple, even too basic, but it was healthy. Therefore, it was a source of inspiration for my own development of <strong>GuppY</strong>.<br />
	<br />
	So, at the end, I decided myself to write my own script, with the idea of sharing it with everybody that would be interested, so I tried to get it as \"user friendly\" as I could. And this is how <strong>GuppY</strong> was born <img alt=\"eek\" src=\"inc/img/smileys/eek.gif\" /></p>
");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
