<?php
$type = "ph";
$fileid = "35";
$status = "a";
$creadate = "201210010400";
$moddate = "201210010400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("");
$fielda2 = stripslashes("");
$fieldb1 = stripslashes("Agrumes");
$fieldb2 = stripslashes("Citrus");
$fieldc1 = stripslashes("<p>
	Une jolie photo pleine d\'agrumes de différentes sortes.</p>
");
$fieldc2 = stripslashes("<p>
	A nice photo filled with different citrus fruits.</p>
");
$fieldd1 = stripslashes("citrus.jpg");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
