<?php
$type = "ar";
$fileid = "34";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("<!--04-->Préparer VOTRE GuppY");
$fielda2 = stripslashes("<!--04-->Setup YOUR GuppY");
$fieldb1 = stripslashes("<!--01-->Installation / Migration");
$fieldb2 = stripslashes("<!--01-->Install / Migrate");
$fieldc1 = stripslashes("<p>
	&nbsp;</p>
<center>
	<h3>
		Préparer VOTRE GuppY</h3>
	<h4>
		Installation / Migration</h4>
</center>
<p>
	&nbsp;</p>
<p>
	Ce script permet de vider la base de données de démonstration livrée avec GuppY et de préparer votre base de données vierge.</p>
<p>
	&nbsp;</p>
<p>
	C\'est aussi le script à lancer si vous souhaitez migrer d\'une version antérieure de GuppY. Lisez bien le fichier <a href=\"lisezmoi.html\" target=\"_blank\">lisezmoi.html</a> avant de procéder car, selon les cas, il peut y avoir des étapes préliminaires.</p>
<p>
	&nbsp;</p>
<form action=\"install/install.php?lng=fr\" method=\"post\" name=\"cleanmp\">
	<center>
		<br />
		<input type=\"submit\" value=\"Préparer VOTRE GuppY\" /></center>
</form>
");
$fieldc2 = stripslashes("<p>
	&nbsp;</p>
<center>
	<h3>
		Setup YOUR GuppY</h3>
	<h4>
		Install / Migrate</h4>
</center>
<p>
	&nbsp;</p>
<p>
	This script will delete the current GuppY demonstration database and prepare your new empty database.</p>
<p>
	&nbsp;</p>
<p>
	This script is also the one to be launched if you wish to migrate from an older version of GuppY. Read carefully the <a href=\"readme.html\" target=\"_blank\">readme.html</a> file before going ahead as there are cases in which some preliminary steps are required.</p>
<p>
	&nbsp;</p>
<form action=\"install/install.php?lng=en\" method=\"post\" name=\"cleanmp\">
	<center>
		<br />
		<input type=\"submit\" value=\"Setup YOUR GuppY\" /></center>
</form>
");
$fieldd1 = stripslashes("right");
$fieldd2 = stripslashes("gyslogo.gif");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
