<?php
$type = "ph";
$fileid = "37";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("");
$fielda2 = stripslashes("");
$fieldb1 = stripslashes("Bonne Année");
$fieldb2 = stripslashes("Happy New Year");
$fieldc1 = stripslashes("Un commentaire est-il nécessaire ?");
$fieldc2 = stripslashes("No comment !");
$fieldd1 = stripslashes("happy_new_year.jpg");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
?>
