<?php
$type = "ph";
$fileid = "36";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("Moto");
$fielda2 = stripslashes("Motorbike");
$fieldb1 = stripslashes("Suzuku GSX-F 600");
$fieldb2 = stripslashes("Suzuku GSX-F 600");
$fieldc1 = stripslashes("La moto actuelle d\'aldweb");
$fieldc2 = stripslashes("The current motorbike of aldweb");
$fieldd1 = stripslashes("motorbike_gsxf.jpg");
$fieldd2 = stripslashes("");
?>
