<?php
$type = "f1";
$fileid = "33";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("Guppy Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("");
$fielda2 = stripslashes("");
$fieldb1 = stripslashes("Boite libre");
$fieldb2 = stripslashes("boite libre");
$fieldc1 = stripslashes("<p>Libre, je suis libre <img src=\"inc/img/smileys/eek.gif\" alt=\"\" border=\"0\" /></p>");
$fieldc2 = stripslashes("<p>Free, I am free <img alt=\"eek\" src=\"inc/img/smileys/eek.gif\"border=\"0\" /></p>");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
?>