<?php
$type = "dn";
$fileid = "30";
$status = "a";
$creadate = "201210150400";
$moddate = "201210142140";
$author = stripslashes("webmaster");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("<!--01-->Manuel");
$fielda2 = stripslashes("<!--01-->Manual");
$fieldb1 = stripslashes("Manuel version française");
$fieldb2 = stripslashes("Manual English version");
$fieldc1 = stripslashes("<p>
	Le manuel pour GuppY 4.6.5, rédigé par Zerg est en téléchargement. Indispensable !</p>
");
$fieldc2 = stripslashes("<p>
	User Manual V46 of&nbsp;Zerg in English version (translated by Killer)</p>
");
$fieldd1 = stripslashes("http://www.freeguppy.org/file/docs/Manuel_GuppY_V465.zip");
$fieldd2 = stripslashes("http://www.freeguppy.org/file/docs/GuppY_Manual_v46en.zip");
$fieldweb = stripslashes("CeCILL");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
