<?php
$type = "ph";
$fileid = "38";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("guppy@freeguppy.org");
$fielda1 = stripslashes("Moto");
$fielda2 = stripslashes("Motorbike");
$fieldb1 = stripslashes("Yamaha Diversion 600");
$fieldb2 = stripslashes("Yamaha Diversion 600");
$fieldc1 = stripslashes("La Diversion fut la toute première moto d\'aldweb");
$fieldc2 = stripslashes("This was aldweb\'s very first motorbike");
$fieldd1 = stripslashes("motorbike_xjs.jpg");
$fieldd2 = stripslashes("");
?>
