<?php
$type = "li";
$fileid = "4";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("1. GuppY");
$fielda2 = stripslashes("1. GuppY");
$fieldb1 = stripslashes("GuppY");
$fieldb2 = stripslashes("GuppY");
$fieldc1 = stripslashes("Le site officiel de <strong>GuppY</strong>.");
$fieldc2 = stripslashes("The official web site of <strong>GuppY</strong>.");
$fieldd1 = stripslashes("http://www.freeguppy.org/");
$fieldd2 = stripslashes("http://www.freeguppy.org/");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
?>