<?php
$type = "ar";
$fileid = "43";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("<!--01-->GuppY");
$fielda2 = stripslashes("<!--01-->GuppY");
$fieldb1 = stripslashes("<!--00 --><font color=\'red\'>LISEZ-MOI</font>");
$fieldb2 = stripslashes("<!--00 --><font color=\'red\'>README</font>");
$fieldc1 = stripslashes("<p>
	<a href=\"#lisezmoi.html\">lisezmoi.html </a><br />
	<a href=\"#CH2\">Chapitre 2</a><br />
	<a name=\"Lisezmoi\"></a></p>
<br />
<div style=\"width: 100%; text-align: center;\">
	&nbsp;<iframe frameborder=\"1\" height=\"600\" scrolling=\"auto\" src=\"lisezmoi.html\" width=\"98%\"></iframe></div>
<br />
<p>
	<a name=\"CH2\"><span style=\"background-color: rgb(255, 255, 0);\"><strong>MERCI DE ME LIRE EN ENTIER !</strong></span></a><br />
	<br />
	Bienvenue sur <strong>GuppY</strong>, le portail web facile et sans base de données.<br />
	<br />
	GuppY est le nouveau nom de miniPortail depuis la version 2.4. Pourquoi donc un nouveau nom ? Tout simplement parce que beaucoup d\'utilisateurs de miniPortail nous ont dit que le qualificatif de \"mini\" les avait trompés sur les réelles et nombreuses fonctionnalités de ce portail web.<br />
	<br />
	Pourquoi le nom de GuppY alors ? Certains ont voulu y voir une signification du genre \"<strong>G</strong>énérateur <strong>U</strong>niversel de <strong>P</strong>ortail en <strong>P</strong>HP, <strong>Y</strong>oupy\" Mais, pour de vrai, GuppY est juste le poisson favori d\'aldweb.<br />
	<br />
	Ce fichier <a href=\"lisezmoi.html\" target=\"_blank\">lisezmoi.html</a> est long et le plus complet possible.<br />
	<br />
	Deux compléments indispensables à ce fichier lisezmoi.html sont :<br />
	- la <a href=\"http://www.freeguppy.org/faq.php?lng=fr\" target=\"_blank\">FAQ</a> GuppY (Foire Aux Questions)<br />
	- le superbe manuel utilisateurs réalisé par Zerg (version française) et WackoJacko (traduction anglaise). Vous les trouverez en téléchargement et en lecture sur le site de GuppY (<a href=\"http://www.freeguppy.org\" target=\"_blank\">http://www.freeguppy.org</a>).</p>
<p>
	<br />
	<span style=\"background-color: rgb(255, 255, 0);\"><strong>Lisez ATTENTIVEMENT cette documentation</strong></span> avant de poser une question sur le <a href=\"http://www.freeguppy.org/fortopic.php?lng=fr\" target=\"_blank\">forum</a> GuppY accessible sur le site de GuppY (<a href=\"http://www.freeguppy.org\" target=\"_blank\">http://www.freeguppy.org</a>). on vous demande gentiment ici de <span style=\"background-color: rgb(255, 255, 0);\"><strong>la lire ATTENTIVEMENT</strong></span> parce que plus de 90% des questions posées sur le forum GuppY ont leur réponse dans cette documentation.<br />
	<br />
	Merci de ne pas m\'écrire personnellement un e-mail pour des questions liées à la compréhension ou à l\'utilisation de GuppY, ma boîte aux lettres étant en permanence saturée de messages et mon temps disponible pour vous répondre étant compté !<br />
	<br />
	Un membre de l\'équipe GuppY ou un autre utilisateur vous répondra sur le <a href=\"http://www.freeguppy.org/fortopic.php?lng=fr\" target=\"_blank\">forum</a> bien plus vite et souvent bien mieux que je ne saurais le faire. En plus, dans ce cas, c\'est l\'ensemble de la communauté des utilisateurs GuppY qui profite de votre question et des réponses apportées. Mais, avant de poser votre question, respectez notre travail et <span style=\"background-color: rgb(255, 255, 0);\"><strong>vérifiez bien que vous avez lu ATTENTIVEMENT la documentation disponible</strong></span>. J\'espère avoir été clair sur ce sujet !<br />
	<br />
	Pour les remerciements et autres commentaires sympathiques, pensez au <a href=\"http://www.freeguppy.org/guestbk.php?lng=fr\" target=\"_blank\">Livre d\'Or</a> du site GuppY ou de mon site personnel avant de m\'écrire personnellement... Merci !<br />
	<br />
	Enfin, si vous tenez vraiment à nous écrire, merci d\'utiliser l\'adresse e-mail <strong>guppy[at]freeguppy.org</strong> qui est accessible à l\'ensemble de la GuppY Team.<br />
	<br />
	<br />
	Bonne lecture,<br />
	<br />
	Laurent Duveau (alias aldweb)</p>
");
$fieldc2 = stripslashes("<p>
	<a href=\"#Lisezmoi\">Readme </a><br />
	<a href=\"#CH2\">Chapter 2</a><br />
	<a name=\"Lisezmoi\"></a></p>
<br />
<div style=\"width: 100%; text-align: center;\">
	&nbsp;<iframe frameborder=\"1\" height=\"600\" scrolling=\"auto\" src=\"readme.html\" width=\"98%\"></iframe></div>
<br />
<p>
	Welcome on <b>GuppY</b>, the easy web portal that does not require a database.<br />
	<br />
	GuppY is the new name for miniPortail as from version 2.4. Why did we change the name? Well, it is pretty simple: many miniPortail users told us that the \"mini\" part of the name (which means \"tiny\" in French) mistaked them about the real and numerous features of this web portal.<br />
	<br />
	Why GuppY as a name then ? Some people tried to find some kind of acronym like \"<b>G</b>uppY is a <b>U</b>niversal <b>P</b>HP <b>P</b>ortal for <b>Y</b>oupy\". But, to tell the truth, GuppY is just the favourite fish of aldweb.<br />
	<br />
	This <a href=\"readme.html\" target=\"_blank\">readme.html</a> file is long and as exhaustive as possible.<br />
	<br />
	Two other documentations complement this readme.html file:<br />
	- the GuppY <a href=\"http://www.freeguppy.org/faq.php?lng=en\" target=\"_blank\">FAQ</a> (Frequently Asked Questions)<br />
	- the beautiful user manual written by Zerg (French version) and WackoJacko (English translation). You will find them on the GuppY website (<a href=\"http://www.freeguppy.org\" target=\"_blank\">http://www.freeguppy.org</a>).<br />
	<span style=\"background-color: rgb(255, 255, 0);\"><b>Read CAREFULLY this documentation</b></span> before asking a question o&amp;shy;n the GuppY <a href=\"http://www.freeguppy.org/fortopic.php?lng=en\" target=\"_blank\">forum</a> which is hosted on the GuppY website (<a href=\"http://www.freeguppy.org\" target=\"_blank\">http://www.freeguppy.org</a>). We kindly ask you to <span style=\"background-color: rgb(255, 255, 0);\"><b>read it CAREFULLY</b></span> because more than 90% of the questions raised on the GuppY forum are answered in this documentation.<br />
	<br />
	Thank you for not writing to me personally with an e-mail for asking questions regarding the understanding or the use of GuppY, my e-mailbox is saturated all of the time with e-mails and my free time to answer you being limited !<br />
	<br />
	A member of the GuppY team or another user will answer you much quicker and often much better than I would do on the <a href=\"http://www.freeguppy.org/fortopic.php?lng=en\" target=\"_blank\">forum</a>. In addition, all GuppY users will then benefit from your questions and the provided answers. But, before asking a question, please respect our work and <span style=\"background-color: rgb(255, 255, 0);\"><b>check carefully that you read CAREFULLY all of the available documentation</b></span>. I hope that I have made this point clear now !<br />
	<br />
	As for saying thank you and for writing other nice comments, please consider posting a message in the <a href=\"http://www.freeguppy.org/guestbk.php?lng=en\" target=\"_blank\">guestbook</a> on the GuppY website or on my personal website before writing to me.... Thanks !<br />
	<br />
	But, if for some reason you really want to write us, please use the <b>guppy@freeguppy.org</b> e-mail address which is accessed by all GuppY Team members.<br />
	<br />
	<br />
	I whish you a good reading,<br />
	<br />
	Laurent Duveau (aka aldweb)</p>
");
$fieldd1 = stripslashes("left");
$fieldd2 = stripslashes("aldsmall.gif");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
