<?php
$type = "ar";
$fileid = "40";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("<!--03-->Insérer une page externe");
$fielda2 = stripslashes("<!--03-->Insert an external page");
$fieldb1 = stripslashes("<!--04-->Page simple");
$fieldb2 = stripslashes("<!--04-->Basic page");
$fieldc1 = stripslashes("<br />
<center>
	<h3>
		Exemple de page externe s\'intégrant à GuppY</h3>
	<h4>
		Page simple</h4>
</center>
<br />
<br />
<p>
	Cette page exemple se trouve dans <strong><em>pages/sample.php</em></strong></p>
<br />
<p>
	Cette page externe s\'affichera dans le cadre central de GuppY. Ceci vous montre comment intégrer dans GuppY des pages externes en PHP ou HTML, en faisant en sorte qu\'elles s\'ouvrent dans le cadre central et non dans une nouvelle fenêtre.</p>
<br />
<form action=\"pages/sample.php?lng=fr\" method=\"post\" name=\"basic\">
	<center>
		<br />
		<input type=\"submit\" value=\"Page simple\" /></center>
</form>
");
$fieldc2 = stripslashes("<br />
<center>
	<h3>
		Sample external page that integrates with GuppY</h3>
	<h4>
		Basic page</h4>
</center>
<br />
<br />
<p>
	This sample page is to be found in <strong><em>pages/sample.php</em></strong></p>
<br />
<p>
	This page will be displayed in GuppY\'s main central box. Thus you see how to integrate external PHP or HTML pages with GuppY, so that these pages are displayed in the main box and not in a new window.</p>
<br />
<form action=\"pages/sample.php?lng=en\" method=\"post\" name=\"basic\">
	<center>
		<br />
		<input type=\"submit\" value=\"Basic page\" /></center>
</form>
");
$fieldd1 = stripslashes("right");
$fieldd2 = stripslashes("gysample.gif");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
