<?php
$type = "f2";
$fileid = "47";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("");
$fielda2 = stripslashes("");
$fieldb1 = stripslashes("GuppY \'allégé\'");
$fieldb2 = stripslashes("\'Light\' GuppY");
$fieldc1 = stripslashes("<div style=\"text-align: left;\"><strong>GuppY</strong> est aussi disponible en <strong>version mobile</strong>, à l\'affichage allégé, destinée à nos amis aveugles et aux amateurs de PDA.</div>
<a href=\"http://www.freguppy.org\" target=\"_blank\">www.freeguppy.org/<strong>mobile/</strong></a> et  même <a href=\"mobile/index.php?lng=fr\">ici</a><img width=\"15\" height=\"15\" border=\"0\" alt=\"wink\" src=\"inc/img/smileys/wink.gif\" />");
$fieldc2 = stripslashes("<strong>GuppY</strong> comes with a lightened displaying <strong>mobile version</strong> which was made for our blind friends and PDA lovers.<br /><a target=\"_blank\" href=\"mobile/\">www.freeguppy.org/<strong>mobile/</strong></a>");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
?>