<?php
$type = "ar";
$fileid = "42";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("<!--02-->Communauté GuppY");
$fielda2 = stripslashes("<!--02-->GuppY community");
$fieldb1 = stripslashes("<!--03-->Besoin d\'aide ?");
$fieldb2 = stripslashes("<!--03-->Need help?");
$fieldc1 = stripslashes("<p>
	Vous trouverez la réponse aux questions le plus fréquemment posées sur <strong>GuppY</strong> en ligne dans la <a href=\"http://www.freeguppy.org/faq.php?lng=fr\" target=\"_blank\">FAQ <strong>GuppY</strong></a>.<br />
	<br />
	Si vous ne trouvez pas réponse à toutes vos questions dans la FAQ, alors rendez-vous sur le <a href=\"http://www.freeguppy.org/fortopic.php?lng=fr\" target=\"_blank\">Forum <strong>GuppY</strong></a> où l\'ensemble de l\'équipe bénévole de <strong>GuppY</strong> et bien d\'autres utilisateurs se feront un plaisir de vous aider.</p>
");
$fieldc2 = stripslashes("<p>
	Answers to the most commonly asked questions about <strong>GuppY</strong> are to be found online in the <a href=\"http://www.freeguppy.org/faq.php?lng=en\" target=\"_blank\"><strong>GuppY</strong> FAQ</a>.<br />
	<br />
	If you do not find an answer to all of your questions in the FAQ, then you might want to ask them in the <a href=\"http://www.freeguppy.org/fortopic.php?lng=en\" target=\"_blank\"><strong>GuppY</strong> Forum</a> where the whole <strong>GuppY</strong> team and many other users will be more than happy to help you.</p>
");
$fieldd1 = stripslashes("left");
$fieldd2 = stripslashes("gyhelp.gif");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
