<?php
$type = "sp";
$fileid = "46";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("");
$fielda2 = stripslashes("");
$fieldb1 = stripslashes("");
$fieldb2 = stripslashes("");
$fieldc1 = stripslashes("<p>
	<b>GuppY</b>, le portail web kiss sans base de données, est disponible dans la <b>version 4.6.21 </b><img alt=\"smile\" border=\"0\" src=\"inc/img/smileys/smile.gif\" title=\"smile\" /></p>
");
$fieldc2 = stripslashes("<p>
	<b>GuppY</b>, the kiss web portal that requires no database, is now available in <b>Release 4.6.21</b><img alt=\"smile\" border=\"0\" src=\"inc/img/smileys/smile.gif\" title=\"smile\" /></p>
");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
