<?php
$type = "fa";
$fileid = "41";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("Générale");
$fielda2 = stripslashes("General");
$fieldb1 = stripslashes("Où puis-je trouver de l\'aide sur <b>GuppY</b> ?");
$fieldb2 = stripslashes("Where can I find some help about <b>GuppY</b>?");
$fieldc1 = stripslashes("Vous trouverez la réponse aux questions le plus fréquemment posées sur <strong>GuppY</strong> en ligne dans la <a href=\"http://www.freeguppy.org/faq.php?lng=fr\" target=\"_blank\">FAQ <strong>GuppY</strong></a>.<br />
<br />
Si vous ne trouvez pas réponse à toutes vos questions dans la FAQ, alors rendez-vous sur le <a href=\"http://www.freeguppy.org/forum.php?lng=fr\" target=\"_blank\">Forum <strong>GuppY</strong></a> où l\'ensemble de l\'équipe bénévole de <strong>GuppY</strong> et bien d\'autres utilisateurs se feront un plaisir de vous aider.");
$fieldc2 = stripslashes("Answers to the most commonly asked questions about <strong>GuppY</strong> are to be found online in the <a href=\"http://www.freeguppy.org/faq.php?lng=en\" target=\"_blank\"><strong>GuppY</strong> FAQ</a>.<br />
<br />
If you do not find an answer to all of your questions in the FAQ, then you might want to ask them in the <a href=\"http://www.freeguppy.org/forum.php?lng=en\" target=\"_blank\"><strong>GuppY</strong> Forum</a> where the whole <strong>GuppY</strong> team and many other users will be more than happy to help you.");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
?>