<?php
$type = "f3";
$fileid = "48";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("");
$fielda2 = stripslashes("");
$fieldb1 = stripslashes("Boîte libre3");
$fieldb2 = stripslashes("Free box 3");
$fieldc1 = stripslashes("<p>&#160;</p>");
$fieldc2 = stripslashes("<p>&#160;</p>");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
?>