<?php
$type = "li";
$fileid = "44";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("3. Licences");
$fielda2 = stripslashes("3. Licences");
$fieldb1 = stripslashes("Site CeCILL");
$fieldb2 = stripslashes("CeCILL site");
$fieldc1 = stripslashes("<p>Le CEA, le CNRS et l\'INRIA ont élaboré CeCILL, la première licence qui définit les principes d\'utilisation et de diffusion des logiciels libres en conformité avec le droit francais, reprenant les principes de la licence GNU GPL. <br />CeCILL est aussi tout à fait adaptée pour des projets internationaux.  <img src=\"inc/img/smileys/smile.gif\" alt=\"smile\" /></p>");
$fieldc2 = stripslashes("<p>CEA, CNRS and INRIA, three French public research organisations, released CeCILL in july 2004. CeCILL is the first license defining the principles of use and dissemination of Free Software in conformance with French law, following the principles of the GNU GPL license.<br />CeCILL is also perfectly suited to international projects. <img src=\"inc/img/smileys/smile.gif\" alt=\"smile\" /></p>");
$fieldd1 = stripslashes("http://www.cecill.info/index.fr.html");
$fieldd2 = stripslashes("http://www.cecill.info/index.en.html");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
?>