<?php
$type = "li";
$fileid = "5";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("1. GuppY");
$fielda2 = stripslashes("1. GuppY");
$fieldb1 = stripslashes("aldweb Site");
$fieldb2 = stripslashes("aldweb Site");
$fieldc1 = stripslashes("Le site personnel du créateur de <b>GuppY</b>.");
$fieldc2 = stripslashes("The personal web site of the creator of <b>GuppY</b>.");
$fieldd1 = stripslashes("http://www.aldweb.com/");
$fieldd2 = stripslashes("http://www.aldweb.com/");
?>
