<?php
$type = "ar";
$fileid = "55";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("<!--01-->GuppY");
$fielda2 = stripslashes("<!--01-->GuppY");
$fieldb1 = stripslashes("<!--10-->Skins");
$fieldb2 = stripslashes("<!--10-->Skins");
$fieldc1 = stripslashes("<div>
	<strong>Les skins en v4.6 se gèrent de la même manière qu\'en v4.5</strong></div>
<div>
	&nbsp;</div>
<div>
	Quelques précisions pourtant :
	<ul>
		<li>
			Le répertoire skin a été déplacé <span style=\"text-decoration: underline;\">à la racine du site</span> pour plus de commodité.</li>
		<li>
			La position des boites est \"couplée\" à la skin.</li>
		<li>
			Vous pouvez choisir la skin que vous souhaitez configurer.</li>
	</ul>
	<strong>Comment procéder :</strong></div>
<div>
	&nbsp;</div>
<div>
	Les différentes sections de configuration du <strong>\"look\" de votre site</strong> ont été réunies dans une zone commune (<strong>Configuration Skin</strong>).<br />
	<br />
	La première icône, <span style=\"font-weight: bold;\">Config thèmes</span>, permet de fixer les thèmes généraux du site (skin par défaut, smileys et avatars) et les thèmes propres à la skin sélectionnée (icônes, compteurs et curseur).</div>
<br />
<p>
	<span style=\"font-weight: bold;\">Config look</span> vous permet de modifier couleurs et graphismes de la skin en cours <span style=\"font-weight: bold;\">ou de toute autre skin <span style=\"text-decoration: underline;\">standard</span>!</span></p>
<p>
	<strong>N\'oubliez pas de générer la feuille de style</strong> de votre skin par <span style=\"font-weight: bold;\">Config style</span>. C\'est une feuille de style \"générique\" que vous pourrez par la suite modifier (manuellement) ou générer de nouveau.<br />
	Si vous faites des corrections manuelles, souvenez-vous qu\'elles seront perdues si vous régénérez de nouveau le style par la procédure automatique <img alt=\"rolleyes\" src=\"inc/img/smileys/rolleyes.gif\" title=\"rolleyes\" />.<br />
	Il sera peut-être nécessaire de <span style=\"text-decoration: underline;\">rafraîchir</span> la page pour voir le résultat<img alt=\"wink\" src=\"inc/img/smileys/wink.gif\" title=\"wink\" />.<br />
	<br />
	Pour certaines skins la configuration des couleurs et graphismes ne sera peut-être pas possible, son concepteur utilisant des paramètres avancés ou ne souhaitant pas briser l\'harmonie de son travail.</p>
<p>
	<span style=\"font-weight: bold;\">Config style</span> vous permet toutefois de rectifier le style de ces dernières (comme de toutes les autres) manuellement <span style=\"text-decoration: underline;\">à vos risques et périls</span> car cela requiert une solide connaissance du langage css.</p>
<p>
	&nbsp;</p>
<div>
	Concernant la configuration des boîtes , <strong>vous pouvez <span style=\"text-decoration: underline;\">en principe</span> ré-organiser les boîtes de toutes les skins.<br />
	Attention, </strong>pour certaines cela risque de rompre l\'équilibre de l\'ensemble.</div>
<div>
	&nbsp;</div>
<div>
	&nbsp;</div>
<div>
	<span style=\"text-decoration:underline;\">Note personnelle</span> :&nbsp; A ce propos , il est souhaitable que les créateurs de skins n\'incluent plus dans leur <strong>skin.css</strong> un test forçant la bascule à no_skin lorsque l\'on est en admin <img alt=\"frown\" src=\"inc/img/smileys/frown.gif\" title=\"frown\" /><br />
	<br />
	Généralement vous devrez modifier les droits des fichiers de configuration:</div>
<div>
	&nbsp;- confskin.inc et style.css doivent être en 666.</div>
<div>
	&nbsp;</div>
<div>
	&nbsp;</div>
");
$fieldc2 = stripslashes("<p>
	<strong>Skins in v4.6 are dealt with in the same way as in v4.5.</strong></p>
<p>
	<br />
	Here a couple of tips though:</p>
<ul>
	<li>
		&nbsp;&nbsp;&nbsp; The skin directory has been moved to the root of the site for convenience.</li>
	<li>
		&nbsp;&nbsp;&nbsp; The position of the boxes is specific to the skin.</li>
	<li>
		&nbsp;&nbsp;&nbsp; You can choose the skin you want to configure.</li>
</ul>
<p>
	<br />
	<strong>How to proceed:</strong></p>
<p>
	<br />
	The different configuration sections of the \"<strong>look\" of your site </strong>have been gathered in a common area (<strong>Skin Configuration</strong>)<br />
	<br />
	The first icon, <strong>Themes Config</strong>, allows setting the broad themes of the site (default skin, smileys and avatars) and thems specific to the selected skin (icons, counters and pointer).<br />
	<br />
	<strong>Config Look</strong> allows you to change colours and graphics of the current skin or<strong> any other standard skin!</strong><br />
	<br />
	<strong>Do not forget to generate the style sheet of your skin in </strong><strong>Config style.</strong> It is a \"generic\" style sheet you can then edit (manually) or generate again.</p>
<p>
	If you make manual corrections, remember they will be lost if you regenerate new style automatically.<img alt=\"rolleyes\" src=\"inc/img/smileys/rolleyes.gif\" title=\"rolleyes\" />.<br />
	It may be necessary to <span style=\"text-decoration:underline;\">refresh </span>the page to see the outcome.<img alt=\"wink\" src=\"inc/img/smileys/wink.gif\" title=\"wink\" />.<br />
	<br />
	For some skins the color settings and graphics may not be not possible, the designer using advanced settings or unwilling to break the harmony of his work.<br />
	<br />
	<strong>Config Style </strong>however allows you to correct the style of the latter (like all others) manually at your own risk because it requires a solid understanding of css language .<br />
	<br />
	For setting up the boxes, <strong>you can basically re-organise the boxes of all skins.</strong></p>
<p>
	<br />
	<strong>Attention</strong>, for some this may upset the balance of the whole layout.</p>
<p>
	<br />
	<strong>Personal note: I</strong>n this respect, it is desirable that the creators of skins no longer include in their skin.css a test forcing swapping to no_skin when in admin. <img alt=\"frown\" src=\"inc/img/smileys/frown.gif\" title=\"frown\" /><br />
	<br />
	You will usually have to change the chmods of configuration files:<br />
	- Confskin.inc style.css and must be in 666.</p>
");
$fieldd1 = stripslashes("left");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
