<?php
$type = "bl";
$fileid = "56";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("Nouvelles");
$fielda2 = stripslashes("News");
$fieldb1 = stripslashes("Bienvenue sur votre blog");
$fieldb2 = stripslashes("Welcome to your blog");
$fieldc1 = stripslashes("<p>
	Toute l\'équipe de la GuppY Team est heureuse de vous présenter ici le blog qui vous permettra de poster vos billets en toute simplicité.</p>
");
$fieldc2 = stripslashes("<p>
	The GuppY Team is pleased to present here the blog that will allow you to post easily your tickets .</p>
");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
