<?php
$type = "fr";
$fileid = "60";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("4");
$fielda2 = stripslashes("0");
$fieldb1 = stripslashes("Test forum Matériel");
$fieldb2 = stripslashes("2");
$fieldc1 = stripslashes("<p>
	Bonjour,<br />
	<br />
	Sur ce fil toutes les questions concernant la partie \"Matériel\".</p>
<p>
	Cordialement</p>
<p style=\"text-align: right;\">
	La GuppY Team</p>
");
$fieldc2 = stripslashes("");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("v");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
