<?php
$type = "li";
$fileid = "6";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("2. Serveur web");
$fielda2 = stripslashes("2. Web server");
$fieldb1 = stripslashes("EasyPHP");
$fieldb2 = stripslashes("EasyPHP");
$fieldc1 = stripslashes("<b>EasyPHP</b> est un package d\'installation d\'un serveur web apache, du langage de script PHP et de base de données MySQL (non nécessaire pour <b>GuppY</b>) pour ton PC tournant sous Windows.");
$fieldc2 = stripslashes("<b>EasyPHP</b> is an installation package of an apache web server, of the PHP scripting language and of MySQL database (which is not needed for <b>GuppY</b>) for your PC running the Windows operating system.");
$fieldd1 = stripslashes("http://www.easyphp.org/");
$fieldd2 = stripslashes("http://www.easyphp.org/");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
?>