<?php
$type = "fr";
$fileid = "62";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("6");
$fielda2 = stripslashes("0");
$fieldb1 = stripslashes("Hardware Test forum");
$fieldb2 = stripslashes("2");
$fieldc1 = stripslashes("Hello,<br /><br />This thread on all matters concerning the \"Hardware\".<br /><br />Regards<br /><div style=\"text-align: right;\">The GuppY Team<br /></div>");
$fieldc2 = stripslashes("");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("v");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
