<?php
$type = "fr";
$fileid = "61";
$status = "a";
$creadate = "201210150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("guppy@freeguppy.org");
$fielda1 = stripslashes("5");
$fielda2 = stripslashes("0");
$fieldb1 = stripslashes("Software Test forum");
$fieldb2 = stripslashes("1");
$fieldc1 = stripslashes("<p>
	Hello,<br />
	<br />
	This thread on all matters concerning the \"Software\".</p>
<p>
	Regards<br />
	&nbsp;</p>
<div style=\"text-align: right;\">
	The GuppY Team</div>
");
$fieldc2 = stripslashes("");
$fieldd1 = stripslashes("");
$fieldd2 = stripslashes("v");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
