<?php
$type = "li";
$fileid = "7";
$status = "a";
$creadate = "20121150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("3. Licences");
$fielda2 = stripslashes("3. Licences");
$fieldb1 = stripslashes("GNU Foundation");
$fieldb2 = stripslashes("GNU Foundation");
$fieldc1 = stripslashes("<p>
	Le site de l\'organisation officielle de GNU (GNU\'s Not Unix). Ce sont eux qui o­nt publié la licence publique GNU. Ils défendent les intérêts des logiciels sous GPL. <img alt=\"smile\" src=\"inc/img/smileys/smile.gif\" /></p>
");
$fieldc2 = stripslashes("<p>
	The web site of the GNU (GNU\'s Not Unix) official organization. They are the o­nes who published the GNU public license. They are defending the software packages published under the GPL license.<img alt=\"smile\" src=\"inc/img/smileys/smile.gif\" /></p>
");
$fieldd1 = stripslashes("http://www.gnu.org/");
$fieldd2 = stripslashes("http://www.gnu.org/");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
