<?php
$type = "ar";
$fileid = "8";
$status = "a";
$creadate = "20121150400";
$moddate = "201210150400";
$author = stripslashes("GuppY Team");
$email = stripslashes("webmaster@guppy.cms");
$fielda1 = stripslashes("<!--01-->GuppY");
$fielda2 = stripslashes("<!--01-->GuppY");
$fieldb1 = stripslashes("<!--01 -->Présentation");
$fieldb2 = stripslashes("<!--01 -->Introduction");
$fieldc1 = stripslashes("<p>
	<strong>GuppY</strong> est un petit portail web, voulu facile d\'utilisation pour l\'utilisateur final que vous êtes, et qui <span style=\"text-decoration: underline;\">ne nécessite pas de base de données</span> pour fonctionner.<br />
	<br />
	Ceci permet donc de l\'installer sur tous les hébergeurs Internet (ou presque), la seule contrainte est que votre hébergeur fournisse le service du langage de script PHP.</p>
<br />
<center>
	<p>
		<img alt=\"\" src=\"img/php.gif\" /></p>
</center>
<p>
	<br />
	Nul besoin de s\'y connaître en langage HTML, en configuration de base de données MySQL, en PHP, car <strong>GuppY</strong> offre une interface d\'administration complète et sécurisée pour gérer l\'apparence de votre site et le contenu des différentes rubriques de votre site.</p>
<p>
	&nbsp;</p>
<p>
	<strong>GuppY</strong> propose l\'ensemble des fonctionnalités classiques d\'un portail web :</p>
<p>
	<br />
	- administration différenciée<br />
	- espace membres<br />
	- blog<br />
	- news<br />
	- articles<br />
	- annuaire de liens<br />
	- section téléchargements<br />
	- diaporama de photos<br />
	- livre d\'or<br />
	- forum<br />
	- FAQ<br />
	- sondage<br />
	- compteur de visites<br />
	- compteur de clics et de téléchargements<br />
	- lettre d\'information<br />
	- zone d\'administration<br />
	- etc...<br />
	<br />
	Mais, <strong>GuppY</strong> apporte une gestion ORIGINALE à forte valeur ajoutée : en plus d\'être nativement MULTILANGUES, <strong>GuppY</strong> offre facultativement une <span style=\"text-decoration: underline;\">présentation du contenu BILINGUE</span>, avec un choix des 2 langues d\'affichage.</p>
<p>
	&nbsp;</p>
");
$fieldc2 = stripslashes("<p>
	<strong>GuppY</strong> is a small web portal, meant to be easy to use for the end user that you are, and which <span style=\"text-decoration:underline;\">does not require a database</span> to run.<br />
	<br />
	This architecture allows then to install it on almost all Internet web sites hosters (or almost all of them), the only prerequisite being that your hoster has to provide the PHP scripting language facility.</p>
<center>
	<p>
		<img alt=\"\" src=\"img/php.gif\" /></p>
</center>
<p>
	<br />
	You don\'t need to know HTML, the MySQL database administration or PHP, <strong>GuppY</strong> offers a full and secured administration interface to manage the look &amp; feel of your web site as well as the content of the different headings of your site.<strong>GuppY</strong> offers the standard functionalities of a web portal :</p>
<p>
	<br />
	- multi administration<br />
	- members area<br />
	- blog<br />
	- news<br />
	- papers<br />
	- links<br />
	- downloads<br />
	- photos display<br />
	- guestbook<br />
	- forum<br />
	- FAQ<br />
	- poll<br />
	- visits counter<br />
	- clics counter, downloads counter<br />
	- newsletter<br />
	- admin area<br />
	- etc...<br />
	<br />
	Furthermore, <strong>GuppY</strong> provides a very ORIGINAL management of high added value: in addition to be natively MULTILINGUAL, <strong>GuppY</strong> offers the possibility of a <span style=\"text-decoration:underline;\">BILINGUAL showing of the content</span>, with the choice of the 2 showed languages.</p>
");
$fieldd1 = stripslashes("left");
$fieldd2 = stripslashes("gyslogo.gif");
$fieldweb = stripslashes("");
$fieldmail = stripslashes("");
$fieldmod = stripslashes("");
