<?php
$home1 = stripslashes("<p>
	Bienvenue sur GuppY !!!</p>
<p>
	Guppy est un système de portail web sans base de données fonctionnant sous PHP.</p>
<p>
	Il vous permet de construire facilement un site web totalement dynamique, de qualité professionnelle et entièrement gratuit. <img alt=\"wink\" src=\"inc/img/smileys/wink.gif\" style=\"width:15px; height:15px; border:0px solid;\" /></p>
<p>
	GuppY vous offre une interface d\'administration complète et sécurisée pour gérer l\'apparence de votre site et le contenu de ses différentes rubriques.<br />
	<br />
	Nul besoin de vous y connaître en langage HTML, en configuration de base de données MySQL ni en PHP : GuppY vous offre votre site clés en main, avec son moteur déjà codé.<img alt=\"smile\" src=\"inc/img/smileys/smile.gif\" style=\"width:15px; height:15px; border:0px solid;\" /></p>
<p>
	En un mot, GuppY se charge du contenant, que vous n\'avez plus qu\'à le remplir avec votre contenu.</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
");
$home2 = stripslashes("<p>
	Welcome to GuppY!</p>
<p>
	Guppy is a simple Content Management System;</p>
<p>
	it will allow you to generate very easily a complete and interactive free web portal, GuppY.It requires no database. <img alt=\"wink\" src=\"inc/img/smileys/wink.gif\" style=\"width:15px; height:15px; border:0px solid;\" /></p>
<p>
	It means that it provides a complete and secure administration interface, to design (your website and manage the content of its various sections/headings.</p>
<p>
	You do not need to know HTML or PHP languages nor how to configurate a MySQL database : Guppy offers a \"turnkey\" website, with its already coded motor .<img alt=\"smile\" src=\"inc/img/smileys/smile.gif\" style=\"width:15px; height:15px; border:0px solid;\" /></p>
<p>
	In one word, Guppy takes care of the container so you just have to take care of the content.</p>
<p>
	&nbsp;</p>
<p>
	&nbsp;</p>
");
