<?php
$freetitle1 = stripslashes("GuppY \'allégé\'");
$freetitle2 = stripslashes("\'Light\' GuppY");
$freetext1 = stripslashes("<div style=\"text-align: left;\"><strong>GuppY</strong> est aussi disponible en <strong>version mobile</strong>, &agrave; l\'affichage all&eacute;g&eacute;, destin&eacute;e &agrave; nos amis aveugles et aux amateurs de PDA.<br /></div><a target=\"_blank\" href=\"mobile/\">www.freeguppy.org/<strong>mobile/</strong></a>");
$freetext2 = stripslashes("<strong>GuppY</strong> comes with a lightened displaying <strong>mobile version</strong> which was made for our blind friends and PDA lovers.<br /><a target=\"_blank\" href=\"mobile/\">www.freeguppy.org/<strong>mobile/</strong></a>");
?>