<?php
$special1 = stripslashes("<p>
	<b>GuppY</b>, le portail web kiss sans base de données, est disponible dans la <b>version 4.6.22 </b><img alt=\"smile\" border=\"0\" src=\"inc/img/smileys/smile.gif\" title=\"smile\" /></p>
");
$special2 = stripslashes("<p>
	<b>GuppY</b>, the kiss web portal that requires no database, is now available in <b>Release 4.6.22 </b><img alt=\"smile\" border=\"0\" src=\"inc/img/smileys/smile.gif\" title=\"smile\" /></p>
");
$specialgroup = stripslashes("");
