<?php
/*
    Mind Language Strings - GuppY PHP Script - version 4.0
    CeCILL Copyright (C) 2004-2006 by Laurent Duveau
    Made by Laurent Duveau, Nicolas Alves, Albert Aymard,
	Jean-Michel Misrachi, Isabelle Marchina and Team
      Web site = http://www.freeguppy.org/
      e-mail   = info@aldweb.com

    Version History :            English language strings
      v3.0 (25 February 2004)  : initial release by Laurent Duveau
      v4.0 (06 December 2004)  : no change
*/

if (stristr($_SERVER["SCRIPT_NAME"], "en-mind.inc")) {
  header("location:index.php");
  die();
}

$mind1 = "Admin - Riddle sample Plugin";
$mind2 = "GuppY comes with a few very simple plugins, as examples (for developers) and as embellishment of your GuppY website (for webmasters).";
$mind3 = "I can read in your mind. Don't you believe it? Try! You will be amazed...";
$mind4 = "Accessed by : ";
$mind5 = "A lateral Box, to be configured in";
$mind6 = "Try it :";
$mind7 = "Riddle";
$mind8 = "Riddle Box";
$mind9 = "Give it a try!";
$mind10 = "The machine that reads in your mind";
$mind11 = "1. Think about a number with two digits (example: 54)";
$mind12 = "2. Substract each of these two digits (5 and 4) to the chosen number (example: 54 - 5 - 4 = 45)";
$mind13 = "3. Look for this result in the following table and memorize the corresponding icon";
$mind14 = "4. <B>Concentrate very much on this icon.</B> Then click on the button and the computer will guess it!";
$mind15 = "Guess my thoughts";
$mind16 = "Here is the icon that I could read in your mind:";
$mind17 = "Guess again my thoughts";
?>
