<?php
/*
    Mind Language Strings - GuppY PHP Script - version 4.0
    CeCILL Copyright (C) 2004-2006 by Laurent Duveau
    Made by Laurent Duveau, Nicolas Alves, Albert Aymard,
	Jean-Michel Misrachi, Isabelle Marchina and Team
      Web site = http://www.freeguppy.org/
      e-mail   = info@aldweb.com

    Version History :           French language strings
      v3.0 (25 February 2004)  : initial release by Laurent Duveau
      v4.0 (06 December 2004)  : no change
*/

if (stristr($_SERVER["SCRIPT_NAME"], "fr-mind.inc")) {
  header("location:index.php");
  die();
}

$mind1 = "Admin - Plugin exemple Devinette";
$mind2 = "GuppY est fourni avec quelques plugins très simples, à titre d'exemple (pour les développeurs) et d'embellissement de votre site GuppY (pour les webmasters).";
$mind3 = "Je peux lire dans vos pensées. Vous n'y croyez pas ? Essayez ! Vous n'en reviendrez pas...";
$mind4 = "Accès par :";
$mind5 = "Une boîte latérale, à configurer dans";
$mind6 = "Le voir fonctionner :";
$mind7 = "Devinette";
$mind8 = "Boîte Devinette";
$mind9 = "J'essaye !";
$mind10 = "La machine à lire dans les pensées";
$mind11 = "1. Pensez à un nombre à deux chiffres (exemple : 54)";
$mind12 = "2. Soustrayez chacun de ces deux chiffres (5 et 4) au nombre choisi (exemple : 54 - 5 - 4 = 45)";
$mind13 = "3. Recherchez ce résultat dans la liste et mémorisez le symbole correspondant";
$mind14 = "<B>Concentrez-vous très fort sur ce symbole.</B> Cliquez ensuite sur le bouton et la machine le devinera !";
$mind15 = "Devinez mes pensées";
$mind16 = "Voici le symbole que j'ai lu dans vos pensées :";
$mind17 = "Redevinez mes pensées";
?>
